import xmlbuilder, { XMLDocumentCB } from 'xmlbuilder';
import {
  AdapterConfigSend,
  AdapterConfigSendNSoftwareFtp,
} from '../../shared/model';

const writeSPAdapterConfigNSoftwareFtp = (
  feed: XMLDocumentCB,
  adapterConfig: AdapterConfigSend,
  address: string,
): void => {
  const config = adapterConfig as AdapterConfigSendNSoftwareFtp;
  feed.text(
    xmlbuilder
      .create('CustomProps', { headless: true })
      .ele('AdapterConfig', { vt: 8 })
      .text(
        xmlbuilder
          .create('Config', { headless: true })
          .att('xmlns:xsi', 'http://www.w3.org/2001/XMLSchema-instance')
          .att('xmlns:xsd', 'http://www.w3.org/2001/XMLSchema')
          .ele('Account')
          .up()
          .ele('AfterConnect')
          .up()
          .ele('AfterPut')
          .up()
          .ele('Append', 'False')
          .up()
          .ele('BeforePut')
          .up()
          .ele('ConnectionLifetime', 0)
          .up()
          .ele('Firewall')
          .ele('AutoDetect', 'False')
          .up()
          .ele('FirewallType', 0)
          .up()
          .ele('Host')
          .up()
          .ele('Password', '******')
          .up()
          .ele('Port', 0)
          .up()
          .ele('User')
          .up()
          .up()
          .ele('FTPPort', config.port)
          .up()
          .ele('FTPServer', config.server)
          .up()
          .ele('Other')
          .up()
          .ele('Overwrite', 'True')
          .up()
          .ele('Passive', 'True')
          .up()
          .ele('Password', '******')
          .up()
          .ele('RemoteFile', config.fileName)
          .up()
          .ele('RemotePath', config.path)
          .up()
          .ele('RemoteTempPath')
          .up()
          .ele('RuntimeLicense')
          .up()
          .ele('SSLAcceptServerCert')
          .ele('AcceptAny', 'True')
          .up()
          .ele('StoreType', 0)
          .up()
          .ele('Store', 'MY')
          .up()
          .ele('Subject')
          .up()
          .ele('StorePassword', '******')
          .up()
          .up()
          .ele('SSLCert')
          .ele('Store', 'MY')
          .up()
          .ele('StorePassword', '******')
          .up()
          .ele('StoreType', 0)
          .up()
          .ele('Subject')
          .up()
          .up()
          .ele('SSLStartMode', 3)
          .up()
          .ele('SSOAffiliate', config.ssoAffiliate)
          .up()
          .ele('Timeout', 60)
          .up()
          .ele('TransferMode', 0)
          .up()
          .ele('TransportLog')
          .ele('Location', 'Application')
          .up()
          .ele('LogMode', 3)
          .up()
          .ele('LogType', 1)
          .up()
          .up()
          .ele('URIIdentity', 'FTP://')
          .up()
          .ele('User', config.userName)
          .up()
          .ele('UseSimpleDirList', 'False')
          .up()
          .ele('uri', address)
          .end(),
      )
      .end(),
  );
};

export default writeSPAdapterConfigNSoftwareFtp;
